apiVersion: v1  # the api version to use
kind: Pod # example Deployment / Pod
metadata:
  name: webservice01
  labels:
    name: webby01 # a meta data label name(s)
spec:
  containers:
  -
    name: webby01 # name of container
    image: gcr.io/artful-tractor-220916/webby:01 # name of the image to use
    ports:
     -
       name: webbyport # name for port mapping
       containerPort: 8888  # we mapped this with the port-forward command
       protocol: TCP # TCP or UDP
