apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-pv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-with-pv
  template:
    metadata:
      labels:
        app: nginx-with-pv
    spec:
      containers:
      - name: nginx-with-pv
        image: nginx:1.7.9
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-pv-storage
          mountPath: "/data"
      volumes:
      - name: nginx-pv-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
