apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
data:
  key: QVFENlRydGRjMlBzQWhBQUc4MTdFTE9aaFZkdFMxRDNGeG5yRlE9PQ==   # Replace with your admin key
type: kubernetes.io/rbd
