apiVersion: apps/v1
kind: Deployment
metadata:
   name: webservice
   labels:
     app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 3
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby
        image: gcr.io/artful-tractor-220916/webby:01   # Or use your own webby image!
        ports:
        - containerPort: 80
